version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - sample_db_data:/var/lib/mysql
    ports:
      - '3308:3306'

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - sample_sync:/app:nocopy
      - sample_bundle:/app/bundle
      - sample_node_modules:/app/node_modules
    ports:
      - '3001:3000'
    links:
      - db
volumes:
  sample_sync:
    external: true
  sample_db_data:
    driver: local
  sample_bundle:
    driver: local
  sample_node_modules:
    driver: local
